name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -------------------------
      # Day 1 Checks
      # -------------------------
      - name: Day1 Init
        run: terraform init -input=false
        working-directory: ./day1

      - name: Day1 Format Check
        run: terraform fmt -check
        working-directory: ./day1

      - name: Day1 Validate
        run: terraform validate
        working-directory: ./day1

      - name: Day1 Plan
        run: terraform plan -input=false
        working-directory: ./day1

      # -------------------------
      # Day 2 Checks
      # -------------------------
      - name: Day2 Init
        run: terraform init -input=false
        working-directory: ./day2

      - name: Day2 Format Check
        run: terraform fmt -check
        working-directory: ./day2

      - name: Day2 Validate
        run: terraform validate
        working-directory: ./day2

      - name: Day2 Plan
        run: terraform plan -var-file="dev.tfvars" -input=false
        working-directory: ./day2
